# index of columns for summary table
SMRY_TICKER = 0
SMRY_STATUS = 1
SMRY_NOS = 2
SMRY_INVESTED = 3
SMRY_ALLOC = 4
SMRY_YOC_A = 8
SMRY_ANN_DIV_A = 9
SMRY_ANN_DIV_A_PC = 7
SMRY_YOC_B = 5
SMRY_ANN_DIV_B = 6
SMRY_NAME = 10
SMRY_SECTOR = 11

DIV_TICKER = 0
DIV_FREQ = 1
DIV_YM = 2
DIV_NOS = 3
DIV_DPS = 4
DIV_BEFORE = 5
DIV_YOC_B = 6
DIV_AFTER = 7
DIV_YOC_A = 8
DIV_WHERE = 9
DIV_CHANGE = 10

SIGN_INCR = '+'
SIGN_DECR = '-'
SIGN_SAME = '='
SIGN_UNKNOWN = '?'

ALLOC_COLOR = 'wheat'
# AFTER_TAX_COLOR = 'papayawhip'
AFTER_TAX_COLOR = '#eafaf1'
BEFORE_TAX_COLOR = 'seashell'
INCR_COLOR = '#d8f3dc'
DECR_COLOR = 'mistyrose'
SAME_COLOR = 'honeydew'
UNKNOWN_COLOR = '#edf2fb'
CLOSED_POS_COLOR = '#9c6644'
TOTAL_COLOR = 'bisque'
NEXT_COLOR = 'beige'
